name: Build .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restaurar pacotes
        run: dotnet restore src/MapShare.sln

      - name: Compilar aplicação
        run: dotnet build src/MapShare.sln --configuration Release --no-restore

      # - name: Rodar testes
      # run: dotnet test src/MapShare.sln --configuration Release --no-build --verbosity normal
